_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ANCHOR_GENERATOR:
    SIZES: [[8], [16], [32], [64], [128]]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 512
SOLVER:
  IMS_PER_BATCH: 512
  BASE_LR: 0.01
  STEPS: (7000, 9000)
  MAX_ITER: 10000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 1000
OUTPUT_DIR:
  "./output/faster_rcnn_R_50_FPN_3x_anchor8"